# Generated by Django 6.0.2 on 2026-03-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
