# Generated by Django 6.0.2 on 2026-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_image_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
