# Generated by Django 6.0.2 on 2026-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('ONLINE', 'UPI/Card')], default='COD', max_length=20),
        ),
    ]
