# Generated by Django 6.0.2 on 2026-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_productvariant_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.FloatField(blank=True, help_text='Length in cm', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='tax_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.FloatField(blank=True, help_text='Width in cm', null=True),
        ),
    ]
